### ISSUE TITLE
Remove getVisualization webservice and replace with frontend implementation

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#105]
The plugin currently depends on the custom backend webservice getVisualization. This is the last leftover from "calc and layout in the backend" to "all logic in the frontend" thing we do for a while now.

At the end, there should be no more getVisualization service.

**Comment by stefanrinderle** [comment]
## Webservice replacement

The main issue with SonarQube here is that it does not provide a real tree (althoug the webservice is named "component_tree".

The process is now as follows:
(1) Request the direct children of the root component (only dir, and suprojects)
(2a) For each sub-project, recursively start from (2)
(2b) For each directory, request all the files in the dir

This sounds strange, but please take a closer look at the webservices to discuss this.

## Tree logic

We have to build up a tree based on the path info provided by SQ. This can be done based on the response which is sorted by the path.

After the tree is created, some optimization have to take place:
* Delete empty folders
[ ] Delete empty directories in between (still TODO)
[ ] Sort children for the side bar (still TODO)

## Before / After

* The structure result is better than before because the old "getVisualisation" webservice did not extract the sub-project structure as good as now. 
* Unfortunately, it takes longer to load the info's. But as we do a lot of single webservice calls  and not a long-running bug one, i hope that maybe issue #37 could be solved with this
[ ] Progress info is now possible (still TODO)

**Comment by Ungolianth** [comment]
The longer load times were to be expected, since we have to call SonarQube now from the client. 

To mitigate the load times for the user, maybe we can start to load the tree as soon as the application starts... This way some of the loading times are "hidden" behind the CityBuilder.

**Comment by stefanrinderle** [comment]
First pull request was merged - yeah! Re-opened the issue because there are still some TODOs:

- [ ] Delete empty directories in between
- [ ] Cleanup the names of everything which was named "legacy". As far as i remembered, we said that legacy is kind of a marker for the old "getVisualization java webservice". As it is migrated to frontend logic, i would like to get rid of the "legacy" naming in our code

**Comment by stefanrinderle** [comment]
Both done. Pull request 116 closes this issue.
