### ISSUE TITLE
New scm metric number of commits

### ISSUE THREAD

**Issue by rebse** [stefanrinderle/softvis3d#111]
SoftVis3D 0.8.1 introduced the new metric number of authors. Beside that, another useful scm metric would be the **number of commits** as an indicator for activity. 

Use case 1: A class with high complexity and a lot of activity during the leak period is a hotspot
Use case 2: In legacy code, no commits or a small number of commits during the leak period - means it's not that critical.

**Comment by stefanrinderle** [comment]
Implemented new building color metric for number of commits.
