### ISSUE TITLE
Format Date of Last Commit

### ISSUE THREAD

**Issue by rebse** [stefanrinderle/softvis3d#112]
The Format of the metric Date of Last Commit is something like `1491313578000`, but should be a configurable DateFormat to be readable for humans.

**Comment by stefanrinderle** [comment]
@rebse Thanks for your request. But i do not really get where and what you mean by that, sorry ;-) Could you define where you see "1491313578000" in our plugin?

**Comment by rebse** [comment]
@stefanrinderle Choose `Date of Last Commit` f.e. as metric for Height, load the scene and click on a building. The metric values for that class are shown and you'll see  `Height:1491313578000` instead of a human readable date format.

**Comment by rebse** [comment]
@stefanrinderle After your email today it became clearer. You wrote the plugin uses `../api/metrics/search?f=name,description&p=1` and the response is filtered for INT, FLOAT, PERCENT, MILLISEC, RATING and WORK_DUR. When using the request `http://softvis3d.com/sonar/api/metrics/search?f=name,description&p=1` the response has also the Date of Last Commit (but no value in that case) =
`{"id":"233","key":"last_commit_date","type":"MILLISEC","name":"Date of Last Commit"}`
