### ISSUE TITLE
Format Date of Last Commit

### ISSUE THREAD

**Issue by rebse** [stefanrinderle/softvis3d#113]
@stefanrinderle Sorry closed Issue #112 by mistake, so reopen..

The Format of the metric Date of Last Commit is something like  1491313578000 , but should be a configurable DateFormat to be readable for humans.

* Choose Date of Last Commit  f.e. as metric for Height
* load the scene and click on a building

The metric values for that class are shown and you'll see something like  `Height:1491313578000`  instead of a human readable date format.

Metric definition of "Date of Last Commit":
`{"id":"233","key":"last_commit_date","type":"MILLISEC","name":"Date of Last Commit"}`

**Comment by stefanrinderle** [comment]
I'm still not sure what the use case for the metric "Date of Last Commit" as height of the buildings is, but we still should show the date instead of the milliseconds. Maybe we have also other values which need some formatting.
