### ISSUE TITLE
illustrator.draw(version) blocks UI thread

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#114]
The call `illustrator.draw(version)` in the LayoutProcessor.ts file is blocking the view thread. This leads to the fact that the UI is kind of frozen during the layout computation time. 

This is not a real issue on small projects but if you take the SonarQube source code as example the status goes directly from load measures to the visualization.

**Comment by stefanrinderle** [comment]
I already created a hacky kind of way to solve this in branch https://github.com/stefanrinderle/softvis3d/tree/114_blocking_ui but there should be a better way to do it :-)

**Comment by Ungolianth** [comment]
My first thought were [workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). I've played with this technology a while back when it was far away from being standardised. I'll take another dive into the docs, followed by a sophisticated opinion.

I will also explore the option of introducing concurrency to the [ccv-library](https://github.com/Ungolianth/codecity-visualizer) while keeping it environment independent (node / browser)...

**Comment by Ungolianth** [comment]
Just a quick update: Not much has changed in the subject of concurrency and parallel execution of JavaScript. 

1. JavaScript can be executed concurrent using the event queue, but requires an external API to make use of true parallel (multi threading) code execution.
2. The Event Loop is still blocking for the time of code execution. Here is an [example](https://jsfiddle.net/eo83aqjj/) I prepared using `setTimeout` and `Promise`.
3. There is no environment independent method to achieve real concurrency in JavaScript; as such i cannot update the algorithms of the code city library reliably.
4. In my opinion making use of WebWorkers in the Softvis3d plugin is the way to go from here.

**Comment by stefanrinderle** [comment]
Reimplemented hacky solution on current master. Will be closed.
