### ISSUE TITLE
Road Trimming

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#117]
Today I updated my ccv-library. A new feature (`road.trim`) introduced for evostreet is the option to trim roads, that won't lead to any content.

Until today the roads size was exactly the size of it's containing package (recursive algorithm). Now we can trim some of those roads in an attempt to make the visualisation more appealing / less complex.

@stefanrinderle What's your opinion on this?

![image](https://cloud.githubusercontent.com/assets/13331717/26035796/7e8f06ca-38d2-11e7-8132-ea631262968b.png)

![image](https://cloud.githubusercontent.com/assets/13331717/26035811/e2c859ac-38d2-11e7-96a8-27872cb4242d.png)

**Comment by stefanrinderle** [comment]
I really like it and it would be great to use it in the SoftVis3d plugin.
