### ISSUE TITLE
More color choices for the color of the buildings

### ISSUE THREAD

**Issue by eitsch** [stefanrinderle/softvis3d#135]
Hello stefan,

thank you very much for this fine plugin and your effort to keep it going! I know a bunch of people which are very happy when they are able to contemplate about the conclusions they see when comparing squaremeter-footprint and tower-height **and color** of our cities :)

Everytime when we do that i myself am a bit bummed as i am struggling with the color part ... my red/green abilities are more "semi-available", sadly.

I was motivated to write this issue here after having read #28 and my amusement concerning the issue title(s), tho :)

As such is, i would like to "issue" two things ... 
* is there a way to dig into the installed jar and change some css-styling to change redgreen to blueyellow for example?
* if there is, how do i do it?

* where would i have to search in the codebase to find a place that i could maybe change on my own
* could i do a local build and deploy my own version? what would be the easiest way to do that?

I hope i do not overwhelm with this issue ... some pointing in the right direction would already be well appreciated and helpful!

TIA
eitsch

**Comment by stefanrinderle** [comment]
Hi,

i had a first look at it and it seems to be an easy change. The important class here ist this:

https://github.com/stefanrinderle/softvis3d/blob/6b419b369e0ac26eff85b67f31587d160317e5b7/softvis3d-frontend/src/services/layout/LayoutProcessor.ts

i will try to prepare an option in the settings for that. Two questions here:
* Instead of green, what to use best? RGB would be great.
* Instead of red, what to use best? RGB would be great.
* I would name the config "alternative building colors". If you have a better term here, name it :-)

Thanks for your input.

**Comment by eitsch** [comment]
hi, 

thank you for your quick reply ... i found https://davidmathlogic.com/colorblind/#%230000FF-%23DCDC00 as a nice (and interactive! 👍 ) playground for the colors. The following presented options are rather well discernible for me. (you asked for rgb, but i chose HEX as the values are presented in hex [in the linked source](https://github.com/stefanrinderle/softvis3d/blob/6b419b369e0ac26eff85b67f31587d160317e5b7/softvis3d-frontend/src/services/layout/LayoutProcessor.ts#L486), too. i hope that is ok for you :)

Prio | green alt | red alt
-------- | -------- | -------
my own | #0000FF | #DCDC00
A | #4B0092 | #1AFF1A
B | #0C7BDC | #FFC20A
C | #005AB5 | #DC3220

The first (my own) is a very yellow/blue one i am used to from jenkins blue/yellow buildstatus balls, the others are my personal favourites from the "accessible palettes" you can find in the URL when scrolling down a bit. as my personal choice: blue checkmarks are ok, yellow crosses are "meh" and the questionmark is "undecided" :-)

![grafik](https://user-images.githubusercontent.com/2989328/97928896-32bd4080-1d68-11eb-9048-d8d61b1a92f6.png)

i also found the use of the term "accessible" rather fitting ... so maybe something like "Accessible building color palettes"? idk if it is a _better_ term ... "accessible building colors" would work, too, i think.

**Comment by stefanrinderle** [comment]
![image](https://user-images.githubusercontent.com/2418659/98151650-cc9ffd00-1ed0-11eb-963a-0834dd83800c.png)

[sonar-softvis3d-plugin-1.1.1-SNAPSHOT.jar.zip](https://github.com/stefanrinderle/softvis3d/files/5489697/sonar-softvis3d-plugin-1.1.1-SNAPSHOT.jar.zip)

So, first version of this feature is now implemented.

@eitsch Please test it and give your comments.

**Comment by stefanrinderle** [comment]
Current state will be merged to master to be able to pick up older changes on the plugin and work from there afterwards.

Still TODO's:
* Make configuration option for background color theme in advanced options also
* Define shortcut for building color

**Comment by eitsch** [comment]
hi stefan, some first observations 
- for me the accessible colors are much(!) better discernible
- the meaning of a specific inspected housecolor was more difficult to comprehend (probably because of small range 1-4 leading to big color gradient steps?)
- the color of the focussed house (the "two" but with * to mark the focussed state) might be misinterpretable with an unfocussed housecolor
- maybe a grayscale gradient would be also interesting? grey to near-black?

Numbers are | Number of authors
------------ | -------------
![grafik](https://user-images.githubusercontent.com/2989328/98166542-df71fc00-1ee7-11eb-93ee-320726584857.png) | ![grafik](https://user-images.githubusercontent.com/2989328/98166521-d7b25780-1ee7-11eb-9202-a1e20ba6fd2a.png)

A different observation ... probably better splitted off to a different issue (if at all):
- Pressing "C" to Toggle Color Theme has side effects on the chosen Metric (meaning of housecolor) 
   - alternates between **_C_**overage and **_C_**omplexity in the Metric dropdown
   - alternates between light and dark theme

**Comment by stefanrinderle** [comment]
Thanks for your feedback. 

I merged your color options into the branch. In the end, it would be great if we have maybe 3 possible color options. So please try out what fits best. You should be able to build it yourself with "mvn clean install" and you find the jar after the successful build in sonar-softvis3d-plugin/target. The current jar is attached.

Pressing "C" to Toggle Color Theme has side effects on the chosen Metric (meaning of housecolor)
--> i already also noted this. My plan is to rework the settings anyways and will keep that in mind. Thanks.
[sonar-softvis3d-plugin-1.1.1-SNAPSHOT.jar.zip](https://github.com/stefanrinderle/softvis3d/files/5497846/sonar-softvis3d-plugin-1.1.1-SNAPSHOT.jar.zip)

**Comment by stefanrinderle** [comment]
Hey @eitsch which of the color options would you prefer?

**Comment by eitsch** [comment]
sorry @stefanrinderle i wanted to reply much sooner! i had the chance to try out all colorthemes on a larger codebase and after having played through the different settings me personally would stick with the following two

- "original" blueyellow (BLUEYELLOW_BUILDING_COLOR_THEME -  0x4B0092, 0x1AFF1A)
- grayscale (GRAYSCALE_BUILDING_COLOR_THEME -  0xCCCCCC, 0x191919)

Grayscale to rule out any colormisinterpretations and for me the first blueyellow felt the most discernible.

thank you for considering my input!

**Comment by stefanrinderle** [comment]
Removed the other options. I will do some more features and then create a release.
