### ISSUE TITLE
Project complexity

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#14]
The Project is rather complex, as multiple webpack instances exist, that are spread across the the entire softvis3d-project. Refactoring and extending the plugin would become a lot easier, once the code layout is simplified and dependencies are easily visible.

For discussion I will add the suggested plugin layout once again:
```
softvis3d-sonar
 |
 |--- Backend (Java)
        |--- Sonar-Plugin-Integration
        |--- Backend-Service
 |
 |--- Frontend (webpack)
        |--- User Interface (Initially SonarQube-dependent)
        |--- Softvis-Modell (SonarQube-dependent: Connects to Backend, Load analyzed code structure, Load Metrics, Create & maintain software modell)
        |--- Softvis-Illustrator (Configurations interface for the UI, Finalizes the model for drawing)
        |--- ThreeJS-Renderer (Independent of SonarQube, Provide Services as an interface for the UI)```

**Comment by stefanrinderle** [comment]
Good idea. I would still keep the maven project structure as it is to keep the java backend classes as is for this step:
softvis3d
|--- softvis3d-base
|--- softvis3d-webservice-example
|--- sonar-softvis3d-plugin

As far as i see this, the refactoring described above will remove the frontend/javascript code from softvis3d-base and changes of the UI do not need a build or dependency of softvis3d-base anymore.

This leads to the fact that the webservice-example project is not usable anymore, which is totally ok. To keep that in mind for the future, i created the issue/ticket #15.

**Comment by Ungolianth** [comment]
I've begun merging the webpack-projects on branch [reduce-complexity](../tree/reduce-complexity).

Unfortunately i could not contain myself to straight up refactoring and also fixed the babel-conversion and IE11-Functionality... :grimacing: 

Initially i only combined `npm/model` and `npm/viewer` to a package `frontend`. Taking one step at a time I'd like to merge the newly created webpack project `frontend` and into the `static/threeViewer` project of the package `sonar-softvis3d-plugin`.

Once I'm done, there will be no more Javascript in the package `softvis3d-base`.
@stefanrinderle Is that alright with you?

**Comment by Ungolianth** [comment]
Oh... I did not get any notification on the *thumbs up* reaction. So while waiting i focused my attention to the ccv-library instead of refactoring. :blush: 

Well, I'm pleased with my progress over there and have returned to the softvis-refactoring: The latest push now merges all webpack-projects into a single one. And I'm also happy to report, that it reduces the overall file size of the plugin by ~800kb. 

**One downside:** I broke the `webservice-example`. As the comiler cannot establish a link to the npm package `softvis-frontend` (because it does not exist anymore) the webservice-example is not functional until we begin to extract the components once again.

How strong is the desire, keep the `webservice-example` up and running, while we undergo the upcoming changes?

**Comment by stefanrinderle** [comment]
Hey,

that the webservice-example does not work anymore after the refactoring is in my opinion not an issue at all. This was expected and I'm not sure if we should put any time in this submodule project for now. As already said, I'm not sure if we need module at all - but I also do not want to make this decision now.

So if everything else is working - submit your pull request ;-)

**Comment by stefanrinderle** [comment]
Very good. Thanks.
