### ISSUE TITLE
Problem with sonarqube 8.8

### ISSUE THREAD

**Issue by pethers** [stefanrinderle/softvis3d#152]
metrics api used have been removed or changed.

**Comment by pethers** [comment]
https://jira.sonarsource.com/browse/SONAR-13848

**Comment by pethers** [comment]
Thanks for providing a cool plugin, miss the 3d view but not critical.

**Comment by stefanrinderle** [comment]
Thanks for the info. I will have a look at this within the next weeks hopefully.

**Comment by stefanrinderle** [comment]
Fixed
