### ISSUE TITLE
Bug in Tree Algorithm

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#16]
![2016-06-05 18_10_00-clipboard](https://cloud.githubusercontent.com/assets/13331717/15806830/fa68c9a0-2b4c-11e6-885a-39bb12109b2a.png)

Once i added a second file into the folder a new SubTree was created for `interfaces`. So i assume it's Problem with folders containing only a single file...

------------------------------------------

For reproduction on the softvis 0.5-branch:
```Bash
git clone http://git.ungolianth.de/ungolianth/codecity-visualizer.git
cd codecity-visualizer
git checkout b1b8036d
```

and sonar-properties:
```config
sonar.projectKey=ccv
sonar.projectName=CodeCityVisiualizer
sonar.projectVersion=0.1.3
sonar.sources=src
sonar.sourceEncoding=UTF-8
```

**Comment by stefanrinderle** [comment]
yes - this is an issue (or feature ;-)) of the TreeBuilder. The use case are e.g. java projects with /src/main/java/... structures. I didn't wanted to have disctricts for folders with just one children folder. This is also valid for the street layout.

Fixed:

![16](https://cloud.githubusercontent.com/assets/2418659/15973407/8e1dcaf2-2f43-11e6-8110-71d25928fd12.jpg)

**Comment by stefanrinderle** [comment]
@Ungolianth Please retest and close if fixed.

**Comment by Ungolianth** [comment]
Works like a charm :+1: 

I see the possible value of this behavior though. Gonna evaluate it as an option for the District-Layout in my ccv plugin.

**Comment by Ungolianth** [comment]
I called this phenomena a `snail` (or a `tower` for districts).

The Layout-Algorithm can now prevent the drawing of such structures and will create only a **single** platform or street for it. Beware though: The Model still holds all the elements.

http://git.ungolianth.de/ungolianth/codecity-visualizer/blob/master/src/illustrator/README.md#illustrator

# Example
![2016-06-10 23_00_05-snail](https://cloud.githubusercontent.com/assets/13331717/15978629/a1be7c16-2f5f-11e6-8903-25028f94b4c6.png)
