### ISSUE TITLE
Recreate Frontend

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#20]
The complexity of the Softvis3D-Frontend will grow a lot in the long-term. I intend to provide a lot of configuration options, which can influence the behavior of the plugin at runtime. Looking forward it is not effective to expand on the currently existing code based on AngularJS. We should agree on a future-proof framework and design a structure that meets our needs and goals.

Then we have to determine a strategy to port the existing functionality into the new framework, before we develop new features. Can we do a Big Bang?

**Comment by stefanrinderle** [comment]
I'm currently working on this. Base idea is now:

Maven module: softvis3d-frontend
Description: Frontend code. 
Features: 
* can be build and developed without sonarqube
* can be started in dev mode without the need to deploy it as sonarqube plugin
* really short dev cycle

Maven module: sonar-softvis3d-plugin
Description: Plugin code
Features: 
* uses the build result from softvis3d-frontend
* does everything within the build that the frontend code can be used in SonarQube

**Comment by stefanrinderle** [comment]
I would say that we can close this one now. We have a good setup now and are able to work on the features.

@Ungolianth Please "review" and close.

**Comment by Ungolianth** [comment]
"_reviewed_"
