### ISSUE TITLE
Make Softvis use Districts again

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#21]
The District View was an integral part of the softvis-plugin. We cannot just cut districts, just to replace it with an unknown, _experimental_ Layout.

Bring District-View back and make it somewhat recognizable. Evostreets should still be available (optional!)

**Comment by Ungolianth** [comment]
19b87c9340df25c3da02e02187ebbe2fd7a3cca8 adds the functionality.

The only problem now is the "Click"-Algorithm, when trying to select a platform. The issue might be with my ccv-plugin, as the naming for plattforms & streets is a bit off. Requires a little bit more investigation...

**Comment by stefanrinderle** [comment]
As already commented on the pull request - the click issue should now be solved. I think this bug was already there and now just shown up more clear because of the different layouts. Please retest and, if all good, close this issue.

**Comment by Ungolianth** [comment]
Tested: 
 * IE / Chrome
 * District / Evostreet

Clicking works
