### ISSUE TITLE
Reactivate color metric for buildings

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#23]
I would like to reactivate different colors for the buildings based on metrics. The colors should start with green #00ff00 and go all the way to red #ff0000 based on the max metric etc.

I also would like to discuss the colors if no metric for the color is selected. I would vote for a single color instead of a random color for each platform / package. Why?
- Although there is no information hidden, the colors attract the visual scope of the user. As a result, some users start to think about the colors of the packages although they are random
- The more different "information" (color) is visible, it is harder to understand.

On the other hand, the different colors seperate the packages. What do you think?

I created this new issue to focus on the SQ release. #8 was moved to the second milestone for now as i don't see it as mandatory. Ok?

**Comment by Ungolianth** [comment]
Quick summary from our call:
 * I will remove the Rule "color-per-package" and so initially all Houses have the same color.
 * If it's not too much trouble i will add a few color-options to the frontend (Depending on how difficult it is, to send options from the frontend to the model)
 * If it's possible the following Rules/Metrics come to mind:
  * Package name (I mean, the rule is already there...)
  * Complexity
  * Number of Methods <--> Number of Attributes
  * Lines of Code  <--> Complexity

**Comment by stefanrinderle** [comment]
Look very good and this can be closed. I created #28 as a future feature story based on this.
