### ISSUE TITLE
Prepare requirenments for SonarQube udpate center release

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#24]
According to this documentation http://docs.sonarqube.org/display/DEV/Deploying+to+Update+Center, we have to fulfill the following:

1. Your plugin is open-source
 a. Source is freely accessible
 b. The license is a known FLOSS one (check the list provided by the Open Source Initiative)
 c. There's a public issue tracking system
 d. Documentation is available online
 e. Binaries of each version are accessible somewhere

2. Releases follow open source conventions
 a. A Release Candidate and feedback period are announced prior to each release. 
 b. A "feedback period closed" notice is sent just before the release.
 c. For each release the following must be available:
  1. release notes that reflect all significant changes in the version
  2. plugin jar

3. The key of your plugin should by convention be:
 a. short and unique
 b. lowercase (no camelcase)
 c. composed only of [a-z0-9]
 d. examples: motionchart, php, scmactivity

4. The description of your plugin must not be misleading in terms of content (the code needs to do pretty much what the name and description say it does)

5. Your plugin does not compete with existing SonarSource products (sorry, but we gotta pay the bills somehow)

6. It is analysed on SonarQube.com and the quality gate is green when doing a release
 a. Initial configuration must be requested in a new thread on the SonarQube Google Group

7. It is compatible with the platform requirements (e.g. it runs on the minimum listed JRE)

8. Last but not least: your plugin must be aligned with the goal of the SonarQube platform: management of the technical debt and the quality of the code
 a. To be more precise: every feature of SonarQube is tied to the code, so if your plugin provides data that can't be attached to a source or a test file, then there are chances that your plugin won't be accepted in the Update Center

**Comment by stefanrinderle** [comment]
Lets go through this step by step:

1. Plugin is open source
1a. Source is available here: https://github.com/stefanrinderle/softvis3d
1b. License: GNU LESSER GENERAL PUBLIC LICENSE v3. FLOSS listed license
1c. Issue tracking system: https://github.com/stefanrinderle/softvis3d/issues
1d. Documentation can be found in the README files of the project and here: http://softvis3d.com
1e. Binaries are available here: https://github.com/stefanrinderle/softvis3d/releases

Requirenments under (1.) are met after releasing a 0.5.x version for the udpate center.

2. Releases follow open source conventions
We will prepare a release candidate and announce a feedback period prior release and request to update center including a "feedback period closed" notice afterwards. This is an open todo and will be documented here.

The released are avaiable through github here: https://github.com/stefanrinderle/softvis3d/releases
All released contain the source code, release notes and the plugin jar.

Requirenments under (2.) are met after closing this issue.

3. The key of your plugin is: sonar-softvis3d-plugin-[VERSION].jar
This is short and unique, lowercase (no camelcase) and composed only of [a-z0-9]

Requirenments under (3.) are already met.

4. Description will be part of the email within 

Requirenments under (4.) are met after closing issue #25.

5. I already asked Fabrice Bellingard in May 2015 about this. His answer was that the corresponding commercial plugin "3D City Model plugin is not ours, it is developed and sold by Excentia." 

What i understand from that is that the requirenments under (5.) are already met.

6. (Nemo) url: https://sonarqube.com/overview?id=de.rinderle.softvis3d%3Asoftvis3d
Quality gate is currently green. 

Requirenments under (6.) are met after closing issue #25.

7. Runs on JRE >= 7 to support SQ versions 5.5 and 5.6

Requirenments under (7.) are met.

8. Software visualization is one part of management of the technical debt and the quality of the code. 

Requirenments under (8.) are met.

**Comment by stefanrinderle** [comment]
Open tasks

-     A Release Candidate and feedback period are announced prior to each release.
-     A "feedback period closed" notice is sent just before the release.
-     Prepare release notes that reflect all significant changes in the version and provide the plugin jar

This also includes to write a description for the plugin.
Important: Quality gate has to be green on release.

**Comment by stefanrinderle** [comment]
Request for feedback started: https://groups.google.com/forum/#!topic/sonarqube/EWfPJDGKFd4
Feedback period till Tuesday 28/06.

**Comment by Ungolianth** [comment]
I'm not sure if the changelogs will be required since the plugin has never been in the _Upgrade Center_, therefore they are somewhat redundant...

Nonetheless here are the relevant changes i came up with regarding `v0.4 -> v0.5`:
 * [Feature] New visualization algorithm replaces Graphiz dependency
 * [Feature] New layout "EvoStreet" is available (experimental)
 * [Feature] UI overhaul
 * [Bugfix] Element-Selection is more reliable in all browsers
 * [Change] The number of available color metrics has been selectively reduced
 * [Change] House measurements use a logarithmic scale

This concludes only the changes i was involved in ;-)

**Comment by stefanrinderle** [comment]
Feedback period closed. The missing steps for an update center requests are now done:

- A Release Candidate and feedback period are announced prior to each release.
- A "feedback period closed" notice is sent just before the release.
- Prepare release notes that reflect all significant changes in the version and provide the plugin jar

Update center release requested:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonarqube/T_8WqagrhCc

**Comment by ganncamp** [comment]
FYI, SQ 5.6 now requires Java 8. The plugin seems to run fine, but your comment above re "JRE >= 7" gave me pause

**Comment by stefanrinderle** [comment]
Added the license information to the root pom, the root README file and the homepage (http://softvis3d.com/#/download) as requested via the google groups thread.

The plugin version 0.5.x are intended to work with SQ version 5.5 and 5.6. As it requires Java 7 but also works in a Java 8 environment i do not see an issue here. If it's required to change the release version to SQ 5.6 and higher only and should only work with Java 8, we could change it. But currently i do not get the advantage of that.

**Comment by ganncamp** [comment]
Re license, thx. Re Java, okay.

**Comment by stefanrinderle** [comment]
Update center release done. Yeah.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonarqube/T_8WqagrhCc
