### ISSUE TITLE
Simplify metric scaling and UI

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#34]
PR #33 introduced more/new scaling Methods for metrics modifying building dimensions. While it can be useful, this feature also makes the UI more complex.

We need to simplify the options / interface. (Maybe drop a few useless options)...

Suggestions are very welcome :wink:

**Comment by stefanrinderle** [comment]
You are right, i think mos of the users are overwhelmed with the choices. My first ideas are the following:
- Extend the city tab for more pre-chosen simple options
- Create an evostreet tab for pre-chosen simple options
- I would keep the custom tab to keep the ability to really customize everything

In addition, i think it is very important that we get more information about how the plugin is used. As i do not know if we are allowed to integrate google analystics, i created an thread on the sonarqube google group:
https://groups.google.com/forum/#!topic/sonarqube/ONm7F4wJAZc

**Comment by Ungolianth** [comment]
I wasn't really comfortable with the idea of adding google analytics, as that might dissatisfy a lot of people, scanning their _precious_ source code with SonarQube. So I'm somewhat relieved after reading Ann's [response](https://groups.google.com/d/msg/sonarqube/ONm7F4wJAZc/lDRGZb5kCQAJ).

About the UI: I believe we should make it a little bit more intuitive all around. Maybe by rearranging a few UI elements, hiding hiding unnecessary options (until they are necessary) and maybe have add a few images for explaining things, the UI can't deliver on it's own. Not really having an elaborate proposition right now. It's just the general direction i feel right now.

But all in all: I completely agree with you on the fact, about not removing any customization options. Code cities and software visualization in general can assist in innumerable tasks, as long as you can customize them for your needs.

**Comment by stefanrinderle** [comment]
I just answered Ann and made it clear that we are not actually planning to integrate google analytics now after the responses. I am/was just curious on the possibilities of the sonarqube platform at this point. I hope we at least get some sort of download statistics like the jenkins plugins.

But i think the user feedback is a really import thing we have to think about in the future. We could start with a "feedback" form within the UI and an option to send feedback if an error occured. Just created #35 for that.

About the UI, lets do a meeting. That's far more easier. But I really like your ideas, especially the picture thing.

**Comment by stefanrinderle** [comment]
Will be closed because almost all new created issues and #46
