### ISSUE TITLE
Display environmental Information

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#36]
# Problem
The Code City Environment is highly configurable, so many of it's properties can represent different features. As such we should make the current city configuration clearly visible to the user.

> I know I picked what metrics I'm looking at, but it's difficult for me at least to remember what maps to height and what to breadth.
> -- _Ann at [Google Group](https://groups.google.com/forum/#!topic/sonarqube/ATusUruYHfw)_

# Proposed changes
 * create a legend area/window for the city
 * add status information like a HUD

**Comment by stefanrinderle** [comment]
Will be closed because split into issues: #47, #48, #49
