### ISSUE TITLE
Remove jquery as dependency

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#38]
JQuery is currently used in SoftVis3dScene react component.

Please replace this code and remove jquery from the package.json

**Comment by stefanrinderle** [comment]
@Ungolianth Please review

**Comment by Ungolianth** [comment]
I also removed the jquery-typings (see 6058a1f853ea55d41fe27cd938e269aa8c4e8ab4).
So far running the project works fine and I did not encounter eny errors regarding jQuery 👍
