### ISSUE TITLE
Integrate layoutprocessor and softvis3d model using typescript

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#39]
The only classes which have not be ported to typescript yet are 
- layoutProcessor.js
- softvisdmodel.js

We need this methods to generate the layout. The currently, displayed layout is based on a fixed json file in app.tsx. Plese remove this afterwards.

**Comment by Ungolianth** [comment]
reopened for review.


webpack-dev-server can be configured, to use our demo sonar server as proxy. Example configuration (`config/dev.ts`):
```ts
import config from "./default";

config.env = "development";
config.proxy = "http://softvis3d.com";
config.pathRewrite = {"^/api" : "/sonar/api"};
config.proxyLegacy = false;
config.project = "composer";

export default config;
```

**Comment by stefanrinderle** [comment]
Great, now we have a working version again.
