### ISSUE TITLE
Test coverage issue on CI servers

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#40]
Currently, the CI server build fails if "npm run test:coverage" is executed. 

See TravisCI build: https://travis-ci.org/stefanrinderle/softvis3d/builds/171656619

The npm command can be  adjusted in /softvis3d/softvis3d-frontend/pom.xml

**Comment by Ungolianth** [comment]
Somehow Cygwin had a problem with nyc calling the tests via `npm test`. Calling `mocha` directly fixes this (ccb3338e6e6d2116028be13d8ad636e0cdd168fb).
