### ISSUE TITLE
Frontend code should not be in the subfolder /src/main/resources

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#41]
Currently, the frontend code is in the subfolder structure /src/main/resources. As we build the plugin with maven this is the default folder for that.

It would be cleaner to change this folder structure and have the frontend code in softvis3d/softvis3d-frontend/src/

Adjust default resource folder in pom.

**Comment by stefanrinderle** [comment]
We also have coverage and test infos available in the sonarqube analysis:
http://softvis3d.com/sonar/dashboard/index?id=de.rinderle.softvis3d%3Asoftvis3d-frontend

@Ungolianth: Set it to testing/review in the project board. Please review and close if everything works as expected.

**Comment by Ungolianth** [comment]
Looking good, as far as i can see right now.
