### ISSUE TITLE
CityBuilder page with Profile, Selection for the three metrics and a picture for each layout

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#42]
CityBuilder page with Profile, Selection for the three metrics and a picture for each layout (see picture) 

![20161029_161939](https://cloud.githubusercontent.com/assets/2418659/19835917/8e90a04a-9e92-11e6-955b-d9f177d54974.jpg)
- important only few metrics should be available for the color

**Comment by Ungolianth** [comment]
![image](https://cloud.githubusercontent.com/assets/13331717/20247437/928f7c58-a9cc-11e6-8be4-7e840d7d32c1.png)

A very simple but functional Version for profiles and preview pictures is available.
[Layouts](../blob/master/softvis3d-frontend/src/dtos/Layouts.ts) and [preview pictures](../blob/master/softvis3d-frontend/src/dtos/PreviewPictures.ts) need to be maintained in their own files (for now called dto). They also need to be delivered manually to their components!
