### ISSUE TITLE
Create default profiles with descriptions and metric settings

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#43]
We decided to create default Profiles targeting the most common use cases of the visualization plugin. 

Each profile should have:
- Name
- Description answering what is the use case and how to interpret the visualization is
- Picture used for the description

TODOs:
- Think about and discuss the most common use cases
- Create at least 3 profiles to start

**Comment by stefanrinderle** [comment]
Created a "Common notepad" wiki page to be able to create/discuss the profiles we want to build without commenting here all the time:
https://github.com/stefanrinderle/softvis3d/wiki/Common-notepad

**Comment by stefanrinderle** [comment]
Analysis and Profile definitions with descriptions finished. 
TODO: Profile pictures

**Comment by stefanrinderle** [comment]
This is how the profile selection should work (my opinion) and how it is now implemented. This of course does not mean that this cannot be discussed :-) 

A profile defines
* heigh metric
* width metric
* scale method
* id, name, description (out of scope here)

Change of profile directly via the profile select box:

* Default profiles except custom
  * Selects heigh, width and scale
* Custom profile
  * Does not change any of the current selected values for height, width and scale (copy current values)

Change of layout type or color metric does not change anything on the profile or metrics.

Change of metric value:
* If one of the default profiles is selected
  * Changes the profile automatically to "custom"

Change of scale method
* Does NOT change the profile to custom

As a result the following flow should work:
* Start with default profile
* Change scale method to linear
  * Profile does not change but linear is selected
* Change to "leak period" profile
  * Scale method should be the default one of the "leak period" profile (log)
* Change scale method to linear
  * Profile does not change but linear is selected
* Change base metric to LOC
  * Profile is custom, base metric is LOC, scale method is still linear
* Select default metric
  * All values (metrics and scale) should be back to default as on start

This is how the custom profile behaves on change
* Start with default profile
* Select custom profile
* Change metric height
* Select default profile
* Select custom profile
  * Values are set based on the last preselected profile. We do not save the state of the custom.

But maybe this all confuses the user more than it helps. We could also just set the profiles by default and changes on preselected profiles will stay in the state. This would mean no reset of the scale on the preselected profiles and no reset of metric and scale on custom. I will try to do a short survey with my colleagues next week about this before closing.

**Comment by Ungolianth** [comment]
Did you get any Feedback on the behaviour of the advanced options?

I myself am not too happy with the inconsistency: In my opinion every alteration of a profile is not the _original_ profile, regardless of a changed metric or the scale. I see the different significance of the Attributes, but a customised profile is still a customised profile ;-)

I believe a consistent behaviour is easier to grasp. So if we want the Scaling not to be part of the profile, we should restructure the UI and our data structure to reflect this...

**Comment by stefanrinderle** [comment]
I got really positive feedback on the overall look and feel. Everybody was happy ;-)

I asked some people on the behavior of the profile settings after they tried the software for 5 minutes and nobody really thought about what will change when (which is in principle a good sign). They where happy on how it changes what but could also live with other behaviors.

But i get your point and i am not sure myself. I would propose to keep the current behavior for this release and add a new issue to the next one. Maybe we get some more feedback and decide then if and what to change.

**Comment by Ungolianth** [comment]
What are we doing here? Leave as is for the release and revise for the next version?

**Comment by stefanrinderle** [comment]
Created #83 to revise in the next release.
