### ISSUE TITLE
Advanced config in CityBuilder page

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#46]
The CityBuild needs to have additional/advanced settings. This is the bottom part of the picture here. We need at least the settings we already had in the 0.6 branch.

![20161029_161939](https://cloud.githubusercontent.com/assets/2418659/19835952/986e1d1c-9e93-11e6-9feb-58f7077d2d76.jpg)

**Comment by Ungolianth** [comment]
![image](https://cloud.githubusercontent.com/assets/13331717/21954397/afe5a6f2-da4f-11e6-93d9-9b00fd5c5309.png)

I would leave the advanced options in their current state for release 0.6. We are going to rework a lot of features with 0.7, so even the advanced options will be revised with the new backend.

I would postpone the explanations for advanced options.
@stefanrinderle What is your opinion on this?

**Comment by stefanrinderle** [comment]
Same opinion as you. Let's move the explanations to the next release. Could you create an issue for that and set it to the next milestone?

According changes on this release the profile changes at the time i click on the advanced options select box. I think it would be better if the profile setting would change if a custom metric was selected. I hope you get what i mean ;-) I addition, the profile does never get set to "custom" if the scaling method select box is clicked or the scaling method changes. I think they all should bahve the same: "Change to custom profile after value is changed".

**Comment by Ungolianth** [comment]
Done aaaand done :metal:

**Comment by stefanrinderle** [comment]
Great, i close this one now.
