### ISSUE TITLE
Add links to source, metrics, ... for currently selected object in the top information bar 

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#47]
Show current selected file info with links for the file to source code, folder/package dashboard, ...

![20161029_161948](https://cloud.githubusercontent.com/assets/2418659/19835963/d40df1ee-9e93-11e6-8d1b-b291fba45d09.jpg)

**Comment by cniweb** [comment]
OK, that´s nice for use, too!

**Comment by stefanrinderle** [comment]
## General

The SonarQube pages require the "key" of the component as "id" parameter - sounds strange, but it is what it is. 

Component WS response example:
`{
      "id": "AVHE6Jo2EplJjXTo0Rzw",
      "key": "com.sonarsource:java-markdown:src/test/java/com/sonarsource/markdown/BasicMarkdownParser.java",
      "name": "BasicMarkdownParser.java",
      "qualifier": "UTS",
      "path": "src/test/java/com/sonarsource/markdown/BasicMarkdownParser.java",
      "language":"java"
}`

Example link: http://localhost:9000/code/?id=de.rinderle.softvis3d%3Asoftvis3d&selected=de.rinderle.softvis3d%3Asoftvis3d-base%3Apom.xml

Our backend and frontend code works with the id of the component but the key is required to open new pages. It was relatively easy to add the key for the files, but it would be very hard to get this info for the folders as well. Take a look at the PathWalker for details.

We wanted to add only "easy frontend" stuff to this release cause the backend code will move to the frontend soon. As a result, this issue will only add links for files. There will be no links for folders.  I created another issue to add the link features for folders in a future release (#86).

## The following will be done now

If file:
- [ ] Open source code:

<img width="27" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/23661242/6dbeb7ac-034c-11e7-8bef-d3b0b723b69f.png"> open file

Example link: http://localhost:9000/code/?id=de.rinderle.softvis3d%3Asoftvis3d&selected=de.rinderle.softvis3d%3Asoftvis3d-base%3Apom.xml

- [ ] Open measures page:

<img width="27" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/23661242/6dbeb7ac-034c-11e7-8bef-d3b0b723b69f.png"> open measures

Example link: http://localhost:9000/component_measures?id=de.rinderle.softvis3d%3Asoftvis3d-frontend%3Asrc%2Fstyle%2Fcomponents%2Fbuilder.scss

###  To be discussed:

- [ ] Add a link to the issues of a file or component

**Comment by stefanrinderle** [comment]
Introduces buttons instead of the above icons. This had two reasons:
* I couldn't find the svg for the icon
* i think buttons look better

For the sake of the "Pfadfinderregel" and because i have some time, I will remove the java softvis3d-base module and integrate the classes in the plugin module. We do not longer need the base module. This also makes it easier later to get rid of most of the backend functionality at all.
