### ISSUE TITLE
Top bar - show settings in the top right corner

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#48]
For the start, we only have the Help, CityBuilder button
- CityBuilder opens the CityBuilder
- Help links to a new tab to http://softvis3d.com/#/details/usage

We should also adjust the usage page of the plugin with this issue. And add more informations to it continuously in the future.

**Comment by Ungolianth** [comment]
* Added Help Button
* Updated style for (all) Buttons

Tested with Chrome, Safari and IE (currently no Firefox installed)

**Comment by stefanrinderle** [comment]
Looks good. Closed.
