### ISSUE TITLE
Refactor Toolbar/Sidebar

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#49]
Only tree is included remove everything else. Should be toggleable

![20161029_161948](https://cloud.githubusercontent.com/assets/2418659/19835993/534c1e4a-9e94-11e6-94f8-7239a7aab006.jpg)

**Comment by stefanrinderle** [comment]
Sidebar first step technically done:
- Jump to parent is shown and a link to select the parent object
- If the selected element is a folder, it's childs are displayed
- If the selected element is a file, its containing folder is displayed. The current selected one is bold

As you are much better with the css and design stuff, i would leave this to you. Ok? 

Just let me know if i can help you if any more data is required.

**Comment by Ungolianth** [comment]
I think the sidebar is somewhat presentable for now.

![image](https://cloud.githubusercontent.com/assets/13331717/21296322/83ec4c40-c569-11e6-894d-6606c8a0cfb7.png)

As for the icons: I just _stole_ them from the SonarQube source code. Before proceeding we've got to check if we are actually allowed to use them...

**Comment by Ungolianth** [comment]
TODO: Scrollbar + Overflow-Detection

**Comment by cniweb** [comment]
It would be nice if you could navigate directly to the source file.

**Comment by Ungolianth** [comment]
@cniweb The feature of navigating to source files (or other to sonarqube measures) is already planned in #47.

If you have more specific suggestions feel free to add them to that issue.

**Comment by stefanrinderle** [comment]
Looks good.
