### ISSUE TITLE
Show "legend" at the bottom with current selected metrics

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#50]
![20161029_161956](https://cloud.githubusercontent.com/assets/2418659/19835995/717c2d24-9e94-11e6-86ee-32da8533dee1.jpg)

**Comment by stefanrinderle** [comment]
Legend at the bottom technically done. As you are much better with the css and design stuff, i would leave this to you. Ok?

**Comment by Ungolianth** [comment]
TODO:
 * Show current values here (and remove them from the top bar)
 * center on the visualisation, not on the page/app

**Comment by Ungolianth** [comment]
* BottomBar has been renamed (SceneInformation) and is now part of the Scene-Component
* As such position and with are now dependent on the scene
* Also the values of the currently selected item are displayed next to the metric key

**Comment by stefanrinderle** [comment]
Looks good. But somehow the click on the buildings is shifted and does not match the real click. I checked (just for 10 minutes) but could not why. Do you have an idea where this is comming from? Was ok in revision 3d26856bc7a6002f939c40f3cc2195d7d0c95170.

- I renamed the test cases BottomBar.spec.tsx and BottomBarMetricInfo.spec.tsx
- Same with SceneInformation.tsx

**Comment by Ungolianth** [comment]
ac4c3f193477c7f35d5817f46b298bb64f3996da fixes this. 

The calculation for the click position should be more consistent from now on, as less factors are involved.

**Comment by stefanrinderle** [comment]
Looks great. Thanks for fixing it.
