### ISSUE TITLE
Plain visualization page

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#54]
Link to SonarQube independent page (without Sonarqube header and footer) - just the visualization.

**Comment by stefanrinderle** [comment]
This was a bit harder than i initially though because of the different baseUrls:
* "Within" sonarqube, the variable window.baseUrl is set by SQ
* On the index.html page, this value has to be given as an url parameter

The plain page url is e.g.:
http://softvis3d.com/sonar/static/softvis3d/index.html?projectKey=de.rinderle.softvis3d:softvis3d&baseUrl=/sonar

But by default, the current status of the view is also added:
http://softvis3d.com/sonar/static/softvis3d/index.html?projectKey=de.rinderle.softvis3d:softvis3d&baseUrl=/sonar&metricFootprint=complexity&metricHeight=ncloc&metricColor=none&layout=evostreet&scale=logarithmic&cameraX=557&cameraY=746&cameraZ=587

The new feature is available in the dropdown "Share" under "Open in new plain tab".

**Comment by Ungolianth** [comment]
Looking good 👍
