### ISSUE TITLE
Errorhandling

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#60]
Catch and display errors and Warnings.
 * Loading-Queue is taking to long
 * Exceptions thrown
 * ...

**Comment by stefanrinderle** [comment]
Currently, i do not see any exceptions in the view. What is part of this review?

**Comment by stefanrinderle** [comment]
TODOs:
* If an error occurs during the initial loading phase (load metrics) show error with app status component and give retry solutioon
* If an error occurs during scene layout or loading show error and give settings as retry solution

**Comment by Ungolianth** [comment]
I have moved the WebGLDetection into the app, so that WebGL is checked at the initial load process. Can we show the error popup here as well?

The method in question is `assertRequirementsAreMet` in `src/app.tsx`.

**Comment by stefanrinderle** [comment]
Error processing and loading done. 

* loading refactored. Loading implemented for
  * SonarQube metric service
  * SonarQube visualization service
  * Layout processing
  * Visualization processing
* Error handling defined for
  * WebGL detector
  * SonarQube metric service
  * SonarQube visualization service

**Comment by Ungolianth** [comment]
I'll do a few tests in the browser tomorrow, but when running the unit tests i get a few warnings:

 * **SceneReactions** <br />
    `(node:9799) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'statusText' of undefined`
 * **\<LoadingQueue/\>** <br />
    `[mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX`

**Comment by stefanrinderle** [comment]
The error in the LoadingQueue is because i have to return something in StatusActionQueue.ts on line 45. The example implementations i used did not return a value on done = true because this will not be used anywhere. If i switch to null, everything can be null and this would blow up the code. So i didn't know how to fix that. If you have an idea for this, it would be great.

The error in Scenereactions.spec.ts should be gone now. I mixed up spies and mocks. Now using mocks and no more error messages.

**Comment by Ungolianth** [comment]
# Initial Fix
5ddb2f922a7b608a743b5f99c430c23e70944c73 fixes the warning. By casting the object a few times, we can fool TypeScript.
```TS
return {
    done: true,
    value: undefined
} as any as IteratorResult<T>;
```
-------------------------------------------
# Ultimate Fix
By exposing the iterable interface of the array we don't have to implement the logic ourselfs. Also the return type has been changed from `IterableIterator<StatusAction>` to `IterableIterator<T>`, which was actually intended.
```TS
public [Symbol.iterator](): IterableIterator<T> {
    return this._queue[Symbol.iterator]();
}
```

See 474aba5651f5a6a98421108511bba01b9aac06d7 and  51ed72468356a9bb6cebc09d7fc0f2204fbf7733

**Comment by stefanrinderle** [comment]
Great, thanks for looking into it.

**Comment by Ungolianth** [comment]
Sorry for being so hard on this one. I'm not even certain which criteria were set for this issue / feature. If the _problem_ is to be expected and as such accepted, we can skip it.

When invalidating the JSON vom getVisualisation no scene is rendered and no error message displayed. Instead i get a few errors in `console.error`:
![image](https://cloud.githubusercontent.com/assets/13331717/23143015/53d4e0fc-f7bf-11e6-9fc1-239d306b42ac.png)

Other than that everything works like a charm. The Message + Reload button really useful (for the circumstances).

**Comment by stefanrinderle** [comment]
No worries. I would like to skip this because it's not reproducable without forcing something to break.

But we should keep the error processing in mind at the time we change to the official SQ API for all calls.

**Comment by Ungolianth** [comment]
All right, _common_ errors are processed as expected. Then I'm closing this one.
