### ISSUE TITLE
Window Management (Loader, CityBuilder, Scene, ...)

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#61]
![image](https://cloud.githubusercontent.com/assets/13331717/20466051/8b7de1a8-af6b-11e6-9f60-ac18dc43834f.png)

Actually this issue is just for review purposes, as this (necessary) feature has been implemented with 1b31502e8b4c61d523409b3924d8b8968871688f.

The right now all the windows visibility is stored and calculated in the `WindowStateStore` and distributed through the Softvis3D-Component (previously App). The visibility of components can only be changed via events.

**Comment by stefanrinderle** [comment]
Looks good. The layout looks cool, but needs some improvements. But I would say that this is out of scope here because it's about the window management internally.
