### ISSUE TITLE
Highlight of streets is permanent with EvoStreet

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#68]
When selecting different streets the street and it's _garden-platform_ are highlighted. When selecting another street or house the highlighting is removed from the garden, but not the street.

![image](https://cloud.githubusercontent.com/assets/13331717/22517740/7377eeb4-e8aa-11e6-876a-b631d4ee464d.png)

**Comment by stefanrinderle** [comment]
Works again. The issue was based on the fact that there are multiple selected "scene objects" with the same softvis3d-id in the evostreet visualization. Therefore, the wrangler class had to be extended.

Done and works. Please confirm.

**Comment by Ungolianth** [comment]
Bug is fixed 👍
