### ISSUE TITLE
Discussion about objects as values in SelectBoxBuilder

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#69]
Currently, we save the value of the select box element within the HTML using JSON to be able to access all object properties onChange without searching for the object first. 

* + positive
  * no search for object value based on id

* - negative
  * HTML gets a lot of info especially on profiles
  * return objects are not really object instances. They "only" contain the value.
    * it is not possible to call any method on the returned object
    * so sometimes, it works and sometimes not. e.g. CityBuilderStore set profile

I think it would be better to work on ids here to be able to call methods on all class instances without the possibility that the object is not an instance but only a value wrapper.

@Ungolianth what do you think about this?

**Comment by Ungolianth** [comment]
I'm absolutely with you on this one. I created the SelectBox-Classes (Selectbox, Options, Grouping) with very little react knowledge based on a few tutorials.

Now I believe I can rework the mechanisms, with minimal changes to the public interface of the classes and without overloading the DOM (which is actually only an internal component). Then the objects won't even be serialised and no information is lost.

I've already begun my work on branch a branch.

**Comment by Ungolianth** [comment]
I'm done and quite pleased with the result.
 * No more unnecessary rubbish in the DOM
 * value objects are processed without any impairment
 * tests 🥇
