### ISSUE TITLE
Use window.SonarRequest to request data (>= SQ 6.0)

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#71]
See https://docs.sonarqube.org/display/DEV/Making+Ajax+Request for details.

Example:
`window.SonarRequest
    .getJSON('/api/issues/search')
    .then(function (response) {
      // here 'response' contains the object representing the JSON output
    });`

**Comment by stefanrinderle** [comment]
In general, the switch to the SonarQube-API using the window was easy. It was more difficult to keep the "sandbox" with "yarn start" working. I have a solution now (see dev.example.conf) but it does not compile. 

@Ungolianth Maybe you have an idea here. Tries a lot but it either does comlile, or it does not work.

What i'm still not sure is if we sould really use this. 
Pros:
* Cleaner code as the "baseUrl" param is not needed anymore
* Based on the SQ documentation and should be stable

Cons:
* Proxy dev code
* axios is really small and it works as it is

@Ungolianth What do you think?

**Comment by Ungolianth** [comment]
I think a lot will change with #70. Let's review how we inject the options and separate production from development environment, once we are certain on the structure ;-)

**Comment by stefanrinderle** [comment]
I just realized that this feature would make #54 much harder to achieve, because the window.SonarRequest variable is only available within the sonar "container". This would mean we have to include axios in the production build in any case. 

Ticket will be closed until there are more disadvantages than we would benefit from it. Branch will be deleted.
