### ISSUE TITLE
Release 0.7 polish

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#72]
I would like to discuss and fix some little things prio the feedback phase. Here is my list what i want to change

- [x] Help button should be visible somewhere on the CityBuilder dialog (@ungolianth)
- [x] The metric values in the info bar at the bottom are currently grey and hard to see / recognize. I would suggest to make this more "eye-candy". (@ungolianth)
- [x] Help section on the website should be reworked (stefan)
- [x] Short description text for scale should be added (stefan)
- [x] Get a green quality gate on the [(sonarqube.com server)](https://sonarqube.com/dashboard?id=de.rinderle.softvis3d%3Asoftvis3d) (stefan)
- [ ] Adjust scss settings on our SQ instance http://softvis3d.com/sonar/dashboard/index/de.rinderle.softvis3d:softvis3d and align the code
- [x] Sidebar layout issue on < 900 pixel width (@ungolianth)
- [x] Long folder names behave incorrect _folderUp-Element_ (@ungolianth)
- [x] Feedback button in the upper right corner

**Comment by Ungolianth** [comment]
Sounds reasonable... I'll have a look the two topics, once I'm done with #69.

**Comment by stefanrinderle** [comment]
Did some more tests. 

* Below 900 px in width, the sidebar width is too big
* Help and Setting Buttons not visible if too small

<img width="774" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/22898898/40ab0ac4-f229-11e6-819c-b7e76207e4b4.png">

* If the file name is too long, wrapping is not nice

![grafik](https://cloud.githubusercontent.com/assets/2418659/22899149/1d34291c-f22a-11e6-9701-4e007a936e92.png)

**Comment by Ungolianth** [comment]
Hm... I'll take a look at it. I thought my _dirty_ solution to long filenames would have worked...
(just let it run out of the box and hide the overflow :shipit: )

**Comment by stefanrinderle** [comment]
I checked the SCSS rules on the SQ server. Fixed some issues and deactivated

* http://softvis3d.com/sonar/coding_rules#rule_key=scss%3Asingle-quotes
  * because we use double quotes everywhere else

What do you think about
* http://softvis3d.com/sonar/coding_rules#rule_key=scss%3Acase
* http://softvis3d.com/sonar/coding_rules#rule_key=scss%3Anested-rulesets

and the other ones?

http://softvis3d.com/sonar/component_issues?id=de.rinderle.softvis3d%3Asoftvis3d#resolved=false|types=CODE_SMELL|sinceLeakPeriod=true|languages=scss

I do not have a strong opinion on most of the rules, but we should adjust the SQ config too meet our guidelines. 

@Ungolianth Could you adjust the rules?

**Comment by Ungolianth** [comment]
I could not reproduce the filename issue, but i made a few preemptive changes in 5fe9ae3191475f80253135e0f260dc36decc36fc.
Do you still get the issue with long filenames?

**Comment by stefanrinderle** [comment]
I could reproduce it by adding fixed values in FolderContent.tsx and ParentElement.tsx. Now looks better:

<img width="288" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/22996367/d9092c1e-f3ce-11e6-97ce-0dd981798fae.png">

So from my point of view, this is done.

**Comment by stefanrinderle** [comment]
Checked the current version for release on windows and mac, different SQ versions and different browsers. Looks good. Will create a release and start the request for feedback.

**Comment by stefanrinderle** [comment]
RFF closed - unfortunately we did not get any feedback. But sometimes this is just a good sign that it did not break anything ;-)
So requested the release: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonarqube/0p4XlEuIkVA

I will also close this issue. The only open task, align scss settings on our SQ instance, is not really release dependent.
