### ISSUE TITLE
Standardise term: Base / Width

### ISSUE THREAD

**Issue by Ungolianth** [stefanrinderle/softvis3d#77]
Not only displayed but also in the source code we use "base" and "width" interchangeably.

![image](https://cloud.githubusercontent.com/assets/13331717/22997016/17c5fca0-f3d1-11e6-8446-f9cb68161166.png)

**Comment by stefanrinderle** [comment]
Really good observation. We should definetely fix this to prevent the user from being confused.

I asked some native speakers yesterday about the naming, and the first reaction to the pictures was "footprint". This also maps to the german word "Grundfläche". So my vote would be to rename everything to footprint.

**Comment by Ungolianth** [comment]
Yes, footprint is fitting. I will change all appearances in the source code 👷
