### ISSUE TITLE
Metric value infos in Sidebar

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#78]
In past versions, the sidebar file infos also contained the measure values.

E.g. Filename.java (14 / 12 / 0)

Although this lead to confusion for some users (as they did not recognize what it is) i would like to discuss to add this info again. Use case:

Navigating through the sidebar you could recognize risk files via the values and click on it. With the values being available there, we build a better context between the sidebar and the visualization.

**Comment by Ungolianth** [comment]
To be honest, I'm not sold on this.For one: If I want to compare metric values, I can use the _Measures_ tab in my project overview. It's not a feature I would use the softvis3d plugin for.

The other thing is that the visualisation should take priority; and the broader the sidebar gets, the visualisation is becoming smaller.

**Comment by stefanrinderle** [comment]
We do not need this currently. Closed.
