### ISSUE TITLE
Descriptions for color values

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#79]
We already have decriptions for the profiles. First user tests with the new version showed that we also should add descriptions for the color metric.

Although pretty obvious to us and the description for most of the metrics will be almost the same, especially the "Package name" color setting needs a description. 

In addition, the current text "The building color can be changed dynamically in the view using the combo box in the bottom bar." is more a help text than a description and therefore can be removed.

**Comment by Ungolianth** [comment]
Looking good (fixed with #80)
