### ISSUE TITLE
Integrate scm infos as metric and use it to color the buildings

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#8]
_From @stefanrinderle on November 15, 2015 21:40_

Already started the implementation in sonarqube 0.3.5-SNAPSHOT. Works only for simple analysis. 
Open tasks:
- Changes in the last X days - where X can be selected
- Number of authors - maybe also within a certain period
- Number of commits - maybe also within a certain period

_Copied from original issue: stefanrinderle/sonar-softvis3d-plugin#8_

**Comment by cniweb** [comment]
Hi @stefanrinderle,

the following metrics are also interesting for us:
- Number of authors - maybe also within a certain period
- Number of commits - maybe also within a certain period

Would be nice if you could implement the right soon.

Thanks,
Chris

**Comment by stefanrinderle** [comment]
@cniweb I checked the metrics api from the current version and unfortunately did not find any "number of authors" metric there. I could only find:

{"id":"181","key":"last_commit_date","type":"MILLISEC","name":"Date of Last Commit","domain":"SCM","direction":0,"qualitative":false,"hidden":true,"custom":false}

Maybe you have a great plugin installed which creates the metrics for you. On which SQ version do you run and do you have any plugins installed which could provide this metric? In addition, could you provide the part of the /api/metrics/search command as a did?

Once i can reproduce it, it would be easy to integrate.

**Comment by cniweb** [comment]
We use SonarQube 5.6+ (LTS) and the Git Plugin:
https://docs.sonarqube.org/display/PLUG/Git+Plugin

**Comment by cniweb** [comment]
I think this is interesting:
https://jira.sonarsource.com/browse/SONAR-3580

**Comment by stefanrinderle** [comment]
Thanks for the links and infos. I took a look at the sources scm api, but unfortunately the response requires to calculate the values for "Number of authors" and "Number of commits" on demand and also requires to load the values for each file manually. This will be very time consuming.

It would be easy to integrate the info if it would be available via the metrics api https://sonarqube.com/api/metrics/search?ps=300. But i could not find the metrics authors_count in my instances (5.6.6 / 6.2). Do you?

**Comment by stefanrinderle** [comment]
I have good and bad news about this. The good ones first:

I created a new color metric in SoftVis3d ("Scm number of authors") and implemented the calculation on demand if the color metric is selected in the visualization. The current build can be downloaded [here](http://softvis3d.com/sonar-softvis3d-plugin-0.8.1-SNAPSHOT.jar).

The colors are defined as follows:
* only one author: red because of the bus factor
* 2 authors: still red and risky. Only two guys know the class.
* 3 authors: darker green 
* More than 3 authors: green 

TODO's:
- [ ] Does not work yet if the new color metric is selected from the start. So please open the visualization and then select the new metric.
- [ ] It also does not yet work if you use the new share link ability
- [ ] There is something strange in the loading logic. The loading is shown very late. So select the new color metric and be patient.

"Bad" news:
* The calculation is very time consuming. It takes about 50 seconds to load.
* Data:

What you requested and we wanted is a metric with a definition like this:
"Number of authors of the file in all time" or "Number of authors of the file within the last X days".

Unfortunately, this data isn't available. What i get from the api as data could be defined as:
"Which author did change the line of a file last". There is no history, just the info of the last commit of the file. This makes a small but important difference. Worst case would be that someone reformats the whole code. My test with the SQ source, on the other side, showed good results. We could check our real-live projects and see if thats an issue. But is is at least very important to explain that correctly to the users. 

TODO:
- [ ] New metric description and help section about it.

The current status of the implementation can be found in the new branch "8-scm-infos".

Technical TODOs:
- [ ] Refactor the SonarQubeServices class. Too much duplicated code.
- [ ] Unit tests.

And a screenshot:
<img width="435" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/24827763/8088db7a-1c50-11e7-832c-9385519e77e0.png">

**Comment by stefanrinderle** [comment]
So, all open todo's are now solved and i updated the current build download available [here](http://softvis3d.com/sonar-softvis3d-plugin-0.8.1-SNAPSHOT.jar

## Summarize feature

"Number of authors of the file in all time" or "Number of authors of the file within the last X days" is not possible because only the scm blame info is available. The new metric color name and description is as follows:
Number of authors (blame): Number of authors based on the SCM blame info. See help page for details.
Unfortunately, the info is only available file by file. This results in long loading times (SonarQube project as an example about 50 seconds).

I also created a info about this in the help section [on our project page](http://softvis3d.com/#/help)

### Technical summary

* New sonar backend service to gather the required data
* New metric values will be calculated and added to the existing project infos

* Added a progress info ability to the loading screen
* "Load scm metrics" adds progress info to loading screen

* Checked that the backend services do not request the same data again.
** SCM metrics will only be calculated once as long as the base infos are not loaded again
** The backend visualization service will not be called again if the data does not change (e.g. on just a layout change)

## Versions

Normally, i would merge this to the current trunk. But as @cniweb is using the 5.6 LTS, i would merge it first to the 0.8.x branch and then from there to the current trunk. This would allow us to create a new 0.8.x release with the feature included.

**Comment by cniweb** [comment]
@rebse we can review the new feature!

**Comment by Ungolianth** [comment]
@cniweb - Just in case you did not get any notifications on this feature yet: Stefan released a new [version](https://github.com/stefanrinderle/softvis3d/releases/tag/softvis3d-0.8.1) on Github; it may be a while until this update is also released to the SonarQube Update Center (because the release process  over there is quite stressful).


@stefanrinderle - Do you intend to merge the [scm branch](https://github.com/stefanrinderle/softvis3d/tree/8-scm-infos) into the master as well? Right now it's only available in Version 0.8 and the feature would therefore be "dropped" in 0.9 again.

**Comment by stefanrinderle** [comment]
@Ungolianth Thanks for merging the changes. I wanted to do this today, but you already did it ;-)

Version 0.8.1 will be requested for the update center with the first 0.9 release which i would expect at the end of next week.
