### ISSUE TITLE
Dark theme for visualization

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#81]
It would be great to have "black theme" for the visualization. It's easy to do, because the backsound setting is easy (see Setup.ts).

<img width="544" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/23140379/8260a054-f7b1-11e6-9957-bfe90075f906.png">

What we have to check is where to put the setting for this.

**Comment by Ungolianth** [comment]
I like it.

When we think about the place to implement this, we should keep in mind, that building and platform colors could also profit from a color change. Maybe we can separate or standardise a little bit, to make the whole themable?

**Comment by stefanrinderle** [comment]
I just started to implement this. Currently it look like this:

![image](https://user-images.githubusercontent.com/2418659/32969181-5bd99870-cbe4-11e7-9bb6-1eedad1c6259.png)
![image](https://user-images.githubusercontent.com/2418659/32969200-73e35744-cbe4-11e7-9d30-c4c9931743a8.png)

Functional:
* A color theme currently only changes the background of the scene
* color theme can be changed via the key C if the visualization is focussed
* color theme setting is added to the "share" functionality - direkt link with color theme possible

Standardise:
* Implemented a generic SceneColorTheme class which could be used to extend the functionality

Open Questions
* Should the colors of the info bar ... also change?
* Is the background color dark enough?
* Should the color theme be part of the settings dialog?

@Ungolianth and everybody: What do you think about the open questions?

The code is not committed yet because its not ready and cleaned up.

**Comment by sebastienvermeille** [comment]
@stefanrinderle thank you to implement this! 
I would use a darker grey. 

Here is the "grey/dark" used by some tools I use everyday:

* jira for monitors (fullscreen) : #000000
* intelliJ in dark: #282829
* thunderbird in dark: #181818

Does it render bad with the true black ? Maybe true black in background and some dark blue for the "packages squares"? 

I would be happy to help and contribute to it if I can someway

anyway great job and thank you for doing all of this

**Comment by michael-niemand** [comment]
backgroud could be a little bit darker in my opinion, but it's already looking great!

**Comment by stefanrinderle** [comment]
Thanks guys. I changed the background color to the IntelliJ dark. I like this the most. A true black would be the same color as the base package in the district layout.

In this issue, only the visualization part changes the background color and the color theme can only be changed wihtin the visualization via the C key.

Created #128 to change the other view elements as well.
Created #129 to change the packages / districts / buildings as well.

But as you know: That these issues have been created does not mean that they will be implemented next ;-)

**Comment by sebastienvermeille** [comment]
👍

**Comment by stefanrinderle** [comment]
Branch  merged, closed.
