### ISSUE TITLE
Auto-update and keep visualization settings and camera position

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#82]
Auto-update is absolutely mandatory if the visualization is used on a monitor as dashboard. We also have opened #54 to show just the visualization.

* Reload should happen in a configurable interval
* all settings should be kept (including the camera angle etc.)

Technical:
See #3 
If we would use url parameters for this, it would then also be possible to share certain visualization views using just a link. In addition, this feature would be great for the examples on our website. 

The auto-reload then just need to hard reload the page.

**Comment by Ungolianth** [comment]
Aren't those two separate features? We have already most of what we need to update the visualisation without the user even noticing... Just like we update our color metrics. No need to do a hard page reload (which i believe to be a very ugly thing for JavaScript-Application).

The other thing is the customisable interval. Does it need to be? The app could be checking if a new scan / report is available every few minutes  and reload all data if needed silently by default. No one would be losing anything, everyone wins and we don't have to clutter the UI with the option.

**Comment by stefanrinderle** [comment]
That's right and a good idea - i didn't think this through :-)

**Comment by stefanrinderle** [comment]
# Technical analysis

There is the projects web api including the last analysis date:

http://softvis3d.com/sonar/api/components/show?component=de.rinderle.softvis3d%3Asoftvis3d

`{"component":{"organization":"default-organization","id":"5bf88193-31e5-4733-8b16-10a2790b4be0","key":"de.rinderle.softvis3d:softvis3d","name":"softvis3d","qualifier":"TRK","analysisDate":"2017-08-15T11:56:14+0200","tags":[],"visibility":"public","leakPeriodDate":"2017-04-26T22:22:54+0200"},"ancestors":[]}`

or the project_analyses web api with a much more detailed info in the respone:

http://softvis3d.com/sonar/api/project_analyses/search?project=de.rinderle.softvis3d%3Asoftvis3d

but the first simpler one could be used for this feature.

**Comment by stefanrinderle** [comment]
Implemented and included in the pull request:

* Auto reload every 5 minutes implemented
* Not configurable, always on
* Working in SQ versions >= 6.4

**Comment by stefanrinderle** [comment]
Merged
