### ISSUE TITLE
 Create a feature to reset the view to the starting point (camera)

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#9]
_From @stefanrinderle on November 15, 2015 21:36_

button "r" and key "r" should be available

_Copied from original issue: stefanrinderle/sonar-softvis3d-plugin#7_

**Comment by stefanrinderle** [comment]
Had more issues during the implementation as expected beceause react does only catch the key events on "input"-like fields. Added comments in the code for details and to prevent further work on this.

I also think that the "r" key is enough and that we do not need a button in the view for that. Therefore, ready for review :-)

**Comment by stefanrinderle** [comment]
Some more work to do - see closed pull request https://github.com/stefanrinderle/softvis3d/pull/88

The keydown event is registered to the window: We cannot in good conscience add an Input field, because the event will still trigger anytime I type a "R"...
This also effects other SonarQube fields (eg. search).

**Comment by Ungolianth** [comment]
![image](https://cloud.githubusercontent.com/assets/13331717/24374892/cb0c839a-1336-11e7-8c22-22fedf15dcc1.png)
What do you this? The legend is only visible, when the scene is the active element (and not toggled away).

We still listen to all the keydown elements on `document`, but we only act on them when the Scene is active.

**Comment by stefanrinderle** [comment]
I like it and would use this approach.

The only think is that I'm not sure if the buttons will disturb heavy users because they know which button to press. But would wait for anyone to complain about it before changing it. One possible solution would then be to use a browser cookie or something equivalent to save the "toggle legend" state over sessions.
